name: "build & test"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        id: py
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-python-${{ steps.py.outputs.python-version }}-
          path: |
            ~/.cache/pypoetry/virtualenvs/
            .mypy_cache/

      - name: Install poetry
        run: pipx install --python '${{ steps.py.outputs.python-path }}' poetry

      - name: Fetch dependencies
        run: poetry install

      - name: Test
        run: poetry run pytest

      - name: mypy
        run: poetry run mypy jumia